import { colors, fonts } from '../theme.js';
import Logo from '../components/Logo.jsx';

export default function Emergency({ v }) {
  const bars = Array.from({ length: 9 });
  return (
    <div>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '18px 32px', borderBottom: `1px solid ${colors.border}`, background: '#fff' }}>
        <a href="#" onClick={(e) => { e.preventDefault(); v.go('dashboard')(); }} style={{ fontSize: 13, fontWeight: 700, color: colors.muted }}>← Back to Dashboard</a>
        <Logo height={20} />
      </header>
      <main style={{ maxWidth: 600, margin: '0 auto', padding: '48px 24px 60px' }}>
        <h1 style={{ fontFamily: fonts.serif, fontSize: 30, margin: '0 0 24px', textAlign: 'center' }}>Here's what might help</h1>

        {v.wasCrisis && (
          <div role="status" style={{ fontSize: 13, color: colors.redText, background: colors.redLight, borderRadius: 12, padding: '12px 16px', marginBottom: 20, fontWeight: 600 }}>
            This looked like a crisis moment, so your linked caregiver has been notified.
          </div>
        )}

        <div style={{ background: '#fff', border: `1px solid ${colors.border}`, borderRadius: 20, padding: 28, marginBottom: 20 }}>
          <button
            onClick={() => (v.voicePlaying ? v.stopSpeaking() : v.speakScript())}
            style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 18, background: 'none', border: 'none', padding: 0, cursor: 'pointer' }}
            aria-label={v.voicePlaying ? 'Stop reading script aloud' : 'Read script aloud'}
          >
            <div style={{ display: 'flex', gap: 3, alignItems: 'center', height: 24 }}>
              {bars.map((_, i) => (
                <div
                  key={i}
                  style={{
                    width: 3, height: '100%', borderRadius: 2,
                    background: v.voicePlaying ? colors.green : colors.grayLight,
                    animation: v.voicePlaying ? `coBar ${0.6 + (i % 3) * 0.2}s ease-in-out infinite` : 'none',
                    animationDelay: `${i * 0.06}s`,
                  }}
                />
              ))}
            </div>
            <div style={{ fontSize: 12, color: v.voicePlaying ? colors.green : colors.mutedLight, fontWeight: 700 }}>
              {v.voicePlaying ? 'Playing voice script — tap to stop' : 'Tap to hear this read aloud'}
            </div>
          </button>
          <p style={{ fontSize: 17, lineHeight: 1.7, color: colors.text, margin: 0 }}>{v.currentScript}</p>
        </div>

        {v.voiceError && (
          <div style={{ fontSize: 12, color: colors.redText, background: colors.redLight, borderRadius: 10, padding: '10px 14px', marginBottom: 18 }}>{v.voiceError}</div>
        )}

        <div style={{ display: 'flex', gap: 10, marginBottom: 18 }}>
          <button onClick={v.tryScript} style={{ flex: 2, fontFamily: fonts.sans, fontWeight: 700, fontSize: 15, padding: 15, borderRadius: 12, border: 'none', background: colors.accent, color: '#fff', cursor: 'pointer' }}>I'll try this</button>
          <button onClick={v.regenerateScript} style={{ flex: 1, fontFamily: fonts.sans, fontWeight: 700, fontSize: 14, padding: 15, borderRadius: 12, border: `1.5px solid ${colors.border}`, background: '#fff', color: colors.text, cursor: 'pointer' }}>Give me another idea</button>
        </div>

        {v.triedShown && <div style={{ fontSize: 13, color: colors.green, fontWeight: 700, marginBottom: 18 }}>✓ Logged — we'll check in with you later tonight.</div>}

        <button onClick={v.toggleTrace} style={{ width: '100%', textAlign: 'left', background: colors.bg, border: '1px dashed #D9D3C6', borderRadius: 12, padding: '14px 16px', fontSize: 12, color: colors.mutedLight, cursor: 'pointer', fontFamily: fonts.sans }}>
          Generated by Gemini, personalized using your check-in history. {v.traceOpen ? '▲ Hide reasoning' : '▼ View reasoning'}
        </button>
        {v.traceOpen && (
          <div style={{ background: colors.bg, border: `1px solid ${colors.border}`, borderTop: 'none', borderRadius: '0 0 12px 12px', padding: 16, fontSize: 12, color: colors.muted, lineHeight: 1.6 }}>
            <div style={{ marginBottom: 6 }}>
              <b>Inputs:</b> {v.scriptTrace?.inputs || '30-day conversation history · current transcript · known triggers · past strategies that worked'}
            </div>
            <div>
              <b>Model:</b> {v.scriptTrace?.model || 'gemini-flash-lite-latest'} · <b>Latency:</b> {v.scriptTrace?.latencyMs ? `${v.scriptTrace.latencyMs}ms` : '—'} · <b>Prompt basis:</b> {v.scriptTrace?.promptBasis || 'Given this person\'s risk pattern and history of what helped before, generate one specific, immediate next step in their voice.'}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
